### ISSUE TITLE
Gehören Snippets, die auf eigene Klassen angewiesen sind, hier rein?

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/rex5_snippets#1]
Ich gehe gerade endlich dazu über, wiederkehrende Aufgaben und Code-Schnippsel in eigene Klassen auszulagern. Bspw.:

https://github.com/alexplusde/PlusHelferlein

Ist dies hier der richtige Ort dafür?

**Comment by schuer** [comment]
Hat sich in #5 geklärt: In Tricks ablegen :)
