### ISSUE TITLE
Snippets in Tricks übertragen?

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/rex5_snippets#5]
Dann hätte man nur einen einzigen Anlaufpunkt.

**Comment by skerbis** [comment]
Ja, ich bin dafür:  Als Menüpunkt: Snippets

**Comment by tbaddade** [comment]
> Als Menüpunkt: Snippets

Was ist der Unterschied nochmal zu Tricks?

**Comment by skerbis** [comment]
Snippets sind links zu Gists und sie sind meistens nicht dokumentiert, kommentiert.

**Comment by polarpixel** [comment]
Wäre auch für Zusammenführung.
Ich hatte schon wieder vergessen, dass es die Snippets überhaupt gibt.

**Comment by tbaddade** [comment]
> Snippets sind Links zu Gists und sie sind meistens nicht dokumentiert, kommentiert.

Dann wäre es sinnvoll, die Gists direkt in das Repo zu holen. Sobald das Gist gelöscht wird, wäre das Snippet verloren.

**Comment by skerbis** [comment]
@eaCe Was sagst Du dazu. Immerhin ist es initial Dein Baby?

**Comment by darwin26** [comment]
Ja, bin dafür ... macht Sinn...

**Comment by elricco** [comment]
Dafür 👍

**Comment by alexplusde** [comment]
ok :)

**Comment by skerbis** [comment]
Hmmm .... schaue man sich die aktuellen Snippets mal an, sehe ich aktuell keinen Sinn für eine Übertragung. Der Bloecks-Tipp ist eher etwas für die Bloecks-Doku, Mein yform-Tipp eher was für eine YOrm-Doku (@alexplusde) und der Rest sollte in der regulären Doku sein. Blätternavi evtl. als Trick für REX5 umsetzen.  Kann eigentlich alles weg - oder was meint ihr?

**Comment by alexplusde** [comment]
Ich seh das anders. Die Snippets sind entstanden, weil sie nicht in der Doku zu finden waren. Ich würde sie erst in der Doku sehen wollen, bevor sie im Nirvana der unbearbeiteten Issues verschwinden.

**Comment by schuer** [comment]
Ich würde sie auch erst übertragen, damit die in der History sind. Danach könnte man bei Bedarf wieder ausdünnen.

**Comment by skerbis** [comment]
War machts?

**Comment by schuer** [comment]
Immer der, der fragt ;)

**Comment by skerbis** [comment]
Einfach Copy-Paste?

**Comment by schuer** [comment]
Im Ernst, willst du’s machen? Musst natürlich nicht, ich wollte dich nicht überrumpeln. Falls du nicht magst, gib es einfach weiter. Ich würde es auch übernehmen, wenn niemand will.

Und ja, Copy & Paste aus den Gists heraus.

**Comment by skerbis** [comment]
Ich mach schon,  dieser Blätter-Code müsste auf REX5 gemünzt werden kannst Du das bitte erledigen @schuer, ich muss noch ein wenig Website-Doku schreiben.

**Comment by schuer** [comment]
Ich bin leider so gar nicht richtig im Thema, was die Blättern-Sache angeht. Vielleicht mag das der @rotzek übernehmen, der es initiiert hat?

**Comment by skerbis** [comment]
Ich nehme mein Snippet hier raus. @alexplusde nimmst es für Yorm? ... das Ist bleibt bestehen

**Comment by alexplusde** [comment]
Ähh das Thema Paginierung war vielfältig - sollte da nicht eine allg. Lösung her?

**Comment by skerbis** [comment]
@alexplusde das snippet mach doch nur ein vor- und zurück

**Comment by alexplusde** [comment]
Oh, geht's hier gar nicht um meins? Bin verwirrt.

**Comment by staabm** [comment]
chatten sollte man im slack, nicht im issue ;)

**Comment by skerbis** [comment]
Mein yform-Snippet habe ich an das yform-Doku-Team übergeben. 2 Snippets habe ich bereits übertragen. Fehlt noch das Blättern.

**Comment by skerbis** [comment]
Es gibt bereits eine fertige Artikel-Blättern-Lösung in der Modulsammlung von Oli. Daher würde ich es jetzt so belassen und es nicht übertragen. Aus meiner Sicht könnte Snippets jetzt gelöscht werden und Olis Modulsammlung stattdessen in FOR gepinnt werden.

**Comment by schuer** [comment]
Danke, @skerbis. Dann machen wir das doch jetzt so und löschen dieses Repo.
Danach werden die offenen Tickets weg sein, aber @rotzek, du kannst ja wenn gewollt dein Blättern-Snippts (https://gist.github.com/rotzek/0400357443f453134634ac7238e0422a) auch nachträglich noch zu den Tricks übertragen.
